### ISSUE TITLE
vsClojure build fails when the extension is installed

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#111]
The build process for vsClojure fails when the extension is installed.

Reproduce;
- Install the extension into Visual Studio
- Build the source code for the extension

Screenshot:

![vsclojure-build-fails-when-extension-is-installed](https://f.cloud.github.com/assets/190154/1745278/a29defd8-642b-11e3-9db2-9d4c7bc76a37.PNG)

```
1>------ Rebuild All started: Project: ClojureExtension.Utilities, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ClojureExtension.Parsing, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: ClojureScript Code File, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: ClojureExtension.Debugger, Configuration: Debug Any CPU ------
3>  ClojureScript Code File -> 
3>  ClojureScript Code File -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureScript Code File\bin\Debug\ItemTemplates\CSharp\1033\ClojureScript Code File.zip
2>  ClojureExtension.Parsing -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Parsing\bin\Debug\ClojureExtension.Parsing.dll
5>------ Rebuild All started: Project: vsClojure, Configuration: Debug x86 ------
5>  "C:\Users\fhale\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\yspokz4h.wkd\Runtimes\ClojureCLR-1.5.0\Clojure.Compile" -o "vsClojure.dll" -i "Metadata"
4>  ClojureExtension.Debugger -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Debugger\bin\Debug\ClojureExtension.Debugger.dll
1>  ClojureExtension.Utilities -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Utilities\bin\Debug\ClojureExtension.Utilities.dll
6>------ Rebuild All started: Project: ClojureExtension.Project, Configuration: Debug Any CPU ------
6>  ClojureExtension.Project -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Project\bin\Debug\ClojureExtension.Project.dll
7>------ Rebuild All started: Project: ClojureExtension.Editor, Configuration: Debug Any CPU ------
7>  ClojureExtension.Editor -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Editor\bin\Debug\ClojureExtension.Editor.dll
8>------ Rebuild All started: Project: ClojureExtension.Repl, Configuration: Debug Any CPU ------
9>------ Rebuild All started: Project: ClojureExtension.Tests, Configuration: Debug Any CPU ------
9>  ClojureExtension.Tests -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Tests\bin\Debug\ClojureExtension.Tests.dll
8>  ClojureExtension.Repl -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Repl\bin\Debug\ClojureExtension.Repl.dll
10>------ Rebuild All started: Project: ClojureExtension.Deployment, Configuration: Debug Any CPU ------
5>  Executing compile (Compiles clojure code files. If an outputAssemblyName is provided, all included code will be compiled into a single assembly, otherwise each will be output as a separate .clj.dll file):
5>  Unhandled Exception: clojure.lang.Compiler+CompilerException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Language.Intellisense, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
5>     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
5>     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
5>     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
5>     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
5>     at System.Reflection.Assembly.Load(String assemblyString)
5>     --- End of inner exception stack trace ---
5>     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
5>     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
5>     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
5>     at clojure.lang.Reflector.InvokeMethod(MethodInfo info, Object target, Object[] args)
5>     at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval(), compiling: (Metadata.clj:1:1) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Language.Intellisense, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
5>     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
5>     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
5>     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
5>     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
5>     at System.Reflection.Assembly.Load(String assemblyString)
5>     --- End of inner exception stack trace ---
5>     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
5>     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
5>     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
5>     at clojure.lang.Reflector.InvokeMethod(MethodInfo info, Object target, Object[] args)
5>     at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval()
5>     --- End of inner exception stack trace ---
5>     at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval()
5>     at clojure.lang.Compiler.Compile1(TypeBuilder tb, CljILGen ilg, ObjExpr objx, Object form)
5>     at clojure.lang.Compiler.Compile(GenContext context, TextReader rdr, String sourceDirectory, String sourceName, String relativePath)
5>     at clojure.lang.RT.Compile(List`1 cljNames, String assemblyName, Boolean hasMain)
5>     at BootstrapCompile.CompileCommand.Run(String[] remainingArguments)
5>     at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
5>     at BootstrapCompile.Compile.Main(String[] args)
5>C:\Users\fhale\Desktop\temp\vsClojure\vsClojure\vsClojure.cljproj(79,5): error MSB3073: The command ""C:\Users\fhale\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\yspokz4h.wkd\Runtimes\ClojureCLR-1.5.0\Clojure.Compile" -o "vsClojure.dll" -i "Metadata"" exited with code -532462766.
5>Done building project "vsClojure.cljproj" -- FAILED.
5>
10>  ClojureExtension.Deployment -> 
10>  ClojureExtension.Deployment -> 
10>  ClojureExtension.Deployment -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Deployment\bin\Debug\ClojureExtension.Deployment.dll
10>  Creating intermediate PkgDef file.
10>  Creating VSIX Container...
10>  ClojureExtension.Deployment -> C:\Users\fhale\Desktop\temp\vsClojure\ClojureExtension.Deployment\bin\Debug\ClojureExtension.Deployment.vsix
========== Rebuild All: 9 succeeded, 1 failed, 0 skipped ==========
```

**Comment by speige** [comment]
Microsoft.VisualStudio.Language.Intellisense, Version=10.0.0.0 Should be in the dependencies folder. It's also installed by the vs1020 SDK. I wonder if adding a reference to it in the Metadata.cljproj & marking it "copy local" would fix it. Maybe it works on my machine because the SDK put it in the GAC?

**Comment by frankhale** [comment]
Okay I added the reference to the vsClojure project (the one with metadata.clj), it defaulted to copy local and it did not resolve the problem for me.

**Comment by speige** [comment]
Was this working for you before? I wonder if my changes to CLOJURE_LOAD_PATH could have caused it.

I haven't seen the error on my machine before. Maybe I'll try creating a clean VM install of windows/visual studio tonight & see if I can reproduce it.

**Comment by frankhale** [comment]
It's never worked for me before. I know this because I realized I had to
uninstall before building again. LOL! This is just the first time I've been
looking into what the problem was.

**Comment by frankhale** [comment]
This is weird. I add the reference to the project, it fails to build saying it can't find the reference. The reference looks fine in the references node in the solution explorer. I close the project and reload the project and Visual Studio thinks that it can't find the reference. This is after adding the reference from the dependencies folder. I wonder if there are other missing files from the SDK in that folder?

![vsclojure-project-deps](https://f.cloud.github.com/assets/190154/1745843/be33f842-6434-11e3-833b-8233680ab99f.PNG)

**Comment by speige** [comment]
My main box doesn't have this issue, but I did a fresh install in a VM with Windows 7, VS2013, & VS2013 SDK & I was able to reproduce this issue.

I'll just have to see what's different between my two boxes.

**Comment by speige** [comment]
It looks like it's installed in my box to C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.VisualStudio.Language.Intellisense\v4.0_10.0.0.0__b03f5f7f11d50a3a  I'm assuming VS 2010 SDK did that.

If I copy the file from the dependencies over to this folder, the error changes from "could not load file or assembly" to "object reference not set to an instance of an object". So, it may be progress, but something still seems to be missing, maybe a .dll that Microsoft.VisualStudio.Language.Intellisense.dll is dependent on?

I get the same results by copying it into C:\Users\Devin\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\20fmkrlg.zu1\Runtimes\ClojureCLR-1.5.0 so, that's an option instead of the GAC

However, copying it to \vsClojure-master\vsClojure\bin\Debug gives me the "could not load file or assembly". So, it seems like Clojure.Compile.exe doesn't look in the same folder as the .clj for missing .dll references.

We may have to change metadata.clj to use System.Reflection.Assembly/LoadFrom or System.Reflection.Assembly/LoadFile rather than System.Reflection.Assembly/Load.

Also, putting copy local true on the reference inside vsClojure didn't seem to actually copy the file. I may need to modify the msbuild script for .cljproj files.

**Comment by frankhale** [comment]
Interestingly enough I am not seeing the problem now. The extension is installed and I can build it and the build process is not complaining like it was. Weird!

**Comment by speige** [comment]
Strange.

I'm still able to reproduce it on my clean VM box (only VS2013 & SDK), & I had previously received an email from another developer with the same issue.

Let's leave this open until we find a resolution.

**Comment by frankhale** [comment]
Okay I tried several times to reproduce this with fresh copies of the code from Github but now it's just not producing the error on my box for some reason.

**Comment by speige** [comment]
Frank,

Do you have vs2010 or vs2012 installed on your box? What about the vs2010SDK or vs2012SDK?

I wonder if any of those could be the reason some machines can't compile Metadata.clj and others can.

**Comment by frankhale** [comment]
I have VS 2013 along with the 2013 SDK

**Comment by frankhale** [comment]
This is no longer happening. I don't see much need to keep this open right now.
