### ISSUE TITLE
Compiling master seems broken for me

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#154]
Not sure what is causing this at the moment but the vsClojure project is failing to compile. I'm looking into this now because I was going to do some work on the code today and this is currently a road block. 

It's exiting with the following for me:

```
Error   1   The command ""C:\Users\fhale\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\c4knlytd.tw4\Runtimes\ClojureCLR-1.5.0\Clojure.Compile" -o "vsClojure.dll" -i "Metadata"" exited with code -532462766.    C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure\vsClojure.cljproj   79  6   vsClojure
```

**Comment by frankhale** [comment]
Trying to compile that project on the command line I see the following. Looks like it can't find the SDK Intellisense DLL for some reason. The interesting thing is that this was all working not too long ago. 

```
C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure>C:\Users\fhale\AppData\Local
\Microsoft\VisualStudio\12.0\Extensions\c4knlytd.tw4\Runtimes\ClojureCLR-1.5.0\C
lojure.Compile -o vsClojure.dll -i Metadata

Executing compile (Compiles clojure code files. If an outputAssemblyName is prov
ided, all included code will be compiled into a single assembly, otherwise each
will be output as a separate .clj.dll file):


Unhandled Exception: clojure.lang.Compiler+CompilerException: System.Reflection.
TargetInvocationException: Exception has been thrown by the target of an invocat
ion. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Micr
osoft.VisualStudio.Language.Intellisense, Version=10.0.0.0, Culture=neutral, Pub
licKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find
 the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String cod
eBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName as
semblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolea
n forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at clojure.lang.Reflector.InvokeMethod(MethodInfo info, Object target, Object
[] args)
   at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval(), compiling: (Metadata
.clj:1:1) ---> System.Reflection.TargetInvocationException: Exception has been t
hrown by the target of an invocation. ---> System.IO.FileNotFoundException: Coul
d not load file or assembly 'Microsoft.VisualStudio.Language.Intellisense, Versi
on=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dep
endencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String cod
eBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName as
semblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolea
n forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evid
ence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at clojure.lang.Reflector.InvokeMethod(MethodInfo info, Object target, Object
[] args)
   at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval()
   --- End of inner exception stack trace ---
   at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval()
   at clojure.lang.Compiler.Compile1(TypeBuilder tb, CljILGen ilg, ObjExpr objx,
 Object form)
   at clojure.lang.Compiler.Compile(GenContext context, TextReader rdr, String s
ourceDirectory, String sourceName, String relativePath)
   at clojure.lang.RT.Compile(List`1 cljNames, String assemblyName, Boolean hasM
ain)
   at BootstrapCompile.CompileCommand.Run(String[] remainingArguments)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 command
s, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at BootstrapCompile.Compile.Main(String[] args)
```

**Comment by frankhale** [comment]
Same thing for MSBuild on the command prompt:

```
C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure>msbuild
Microsoft (R) Build Engine version 4.0.30319.33440
[Microsoft .NET Framework, version 4.0.30319.34011]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/21/2014 11:15:04 AM.
Project "C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure\vsClojure.cljproj"
 on node 1 (default targets).
CoreCompile:
  "C:\Users\fhale\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\c4knlytd
  .tw4\Runtimes\ClojureCLR-1.5.0\Clojure.Compile" -o "vsClojure.dll" -i "Metada
  ta"

  Executing compile (Compiles clojure code files. If an outputAssemblyName is p
  rovided, all included code will be compiled into a single assembly, otherwise
   each will be output as a separate .clj.dll file):


  Unhandled Exception: clojure.lang.Compiler+CompilerException: System.Reflecti
  on.TargetInvocationException: Exception has been thrown by the target of an i
  nvocation. ---> System.IO.FileNotFoundException: Could not load file or assem
  bly 'Microsoft.VisualStudio.Language.Intellisense, Version=10.0.0.0, Culture=
  neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The sys
  tem cannot find the file specified.
     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String
  codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawl
  Mark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean
   forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName
   assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCr
  awlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Bool
  ean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, E
  vidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder,
  Boolean forIntrospection)
     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, E
  vidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection
  )
     at System.Reflection.Assembly.Load(String assemblyString)
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] argumen
  ts, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Ob
  ject[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags inv
  okeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at clojure.lang.Reflector.InvokeMethod(MethodInfo info, Object target, Obj
  ect[] args)
     at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval(), compiling: (Metad
  ata.clj:1:1) ---> System.Reflection.TargetInvocationException: Exception has
  been thrown by the target of an invocation. ---> System.IO.FileNotFoundExcept
  ion: Could not load file or assembly 'Microsoft.VisualStudio.Language.Intelli
  sense, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or
   one of its dependencies. The system cannot find the file specified.
     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String
  codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawl
  Mark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean
   forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName
   assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCr
  awlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Bool
  ean forIntrospection, Boolean suppressSecurityChecks)
     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, E
  vidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder,
  Boolean forIntrospection)
     at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, E
  vidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection
  )
     at System.Reflection.Assembly.Load(String assemblyString)
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] argumen
  ts, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Ob
  ject[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags inv
  okeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at clojure.lang.Reflector.InvokeMethod(MethodInfo info, Object target, Obj
  ect[] args)
     at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval()
     --- End of inner exception stack trace ---
     at clojure.lang.CljCompiler.Ast.StaticMethodExpr.Eval()
     at clojure.lang.Compiler.Compile1(TypeBuilder tb, CljILGen ilg, ObjExpr ob
  jx, Object form)
     at clojure.lang.Compiler.Compile(GenContext context, TextReader rdr, Strin
  g sourceDirectory, String sourceName, String relativePath)
     at clojure.lang.RT.Compile(List`1 cljNames, String assemblyName, Boolean h
  asMain)
     at BootstrapCompile.CompileCommand.Run(String[] remainingArguments)
     at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 comm
  ands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsa
  ge)
     at BootstrapCompile.Compile.Main(String[] args)
C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure\vsClojure.cljproj(79,5): er
ror MSB3073: The command ""C:\Users\fhale\AppData\Local\Microsoft\VisualStudio\
12.0\Extensions\c4knlytd.tw4\Runtimes\ClojureCLR-1.5.0\Clojure.Compile" -o "vsC
lojure.dll" -i "Metadata"" exited with code -532462766.
Done Building Project "C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure\vsCl
ojure.cljproj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure\vsClojure.cljproj" (defaul
t target) (1) ->
(CoreCompile target) ->
  C:\Users\fhale\Documents\GitHub\vsClojure\vsClojure\vsClojure.cljproj(79,5):
error MSB3073: The command ""C:\Users\fhale\AppData\Local\Microsoft\VisualStudi
o\12.0\Extensions\c4knlytd.tw4\Runtimes\ClojureCLR-1.5.0\Clojure.Compile" -o "v
sClojure.dll" -i "Metadata"" exited with code -532462766.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.34
```

**Comment by frankhale** [comment]
This is a local machine issue. Going back several commits doesn't resolve it. Adding the IntelliSense dll to the GAC doesn't resolve it either. I'll close this since it's not a vsClojure bug. I guess something has happened to my laptop. My desktop machine was working fine and I'll check it out tonight when I get home.

**Comment by speige** [comment]
I pulled the latest & was able to compile it on my box. I agree, it seems machine-dependent issue. Maybe we should add some of these dlls to a dependency folder rather than assuming developers will have all the required dlls on their machines.

**Comment by frankhale** [comment]
That particular DLL is in the Dependencies folder which is odd. I wasn't
getting this issue until today. I've spent a few hours on it and haven't
resolved it yet.

**Comment by frankhale** [comment]
I just installed VS 2013 on a VM that already had 2010 + 2010 SDK and I can build vsClojure but there are weird build order anomolies and doing a Rebuild from the menu will result in errors because it tries to build projects that depend on other projects and fails. I have to build required projects first and then I can build the deployment one. WOW! So many problems today. I'm not sure I like any of this because I've literally wasted 6 hours and have not been able to come up with any solution really to the current build issues. Hopefully my machine at home still works. I'll definitely try it when I get home because if it's broke I may just lose my mind.

**Comment by frankhale** [comment]
Thankfully vsClojure is building fine on my home computer, LOL!
