### ISSUE TITLE
VS 2012 Crashes on initial startup after install

### ISSUE THREAD

**Issue by jecxjo** [vsClojure/vsClojure#165]
After loading the VSIX installer and restarting Visual Studio the following error message pops up.

![image](https://cloud.githubusercontent.com/assets/1279178/3460977/3cecab08-021d-11e4-8c52-e7b13ec4abeb.png)

Here are the problem details.

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: devenv.exe
  Problem Signature 02: 11.0.61030.0
  Problem Signature 03: 5270a974
  Problem Signature 04: Clojure
  Problem Signature 05: 1.5.0.0
  Problem Signature 06: 52976849
  Problem Signature 07: 1263
  Problem Signature 08: 18
  Problem Signature 09: System.InvalidOperationException
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Only option is to close the program and uninstall the extension.

**Comment by frankhale** [comment]
Just curious, are you using the latest version from the Visual Studio Gallery?

**Comment by jecxjo** [comment]
Yes, I googled vsclojure and went to version 2.1.6 at http://visualstudiogallery.msdn.microsoft.com/0e53eaf6-b031-4d12-84c1-9163db0b757e

Also I'm running Visual Studio Pro 2012, version 11.0.61030.00 Update 4 and .NET Framework version 4.5.50709

**Comment by frankhale** [comment]
Do you mind trying to build from master code and seeing if that still causes the problem?

**Comment by jecxjo** [comment]
Sorry I'm unable to build as the vsClojure, ClojureScript Code File  and ClojureExtension.Deployment projects are not compatible with VS 2012.

**Comment by mark4asp** [comment]
I believe this is the same issue which is now preventing my VS2012 from loading - until after I clean it of the offending extension. The error message box I see is the same one that jecxjo sees (see above). It doesn't matter what kind of project or solution I open, the vsClojure extension crashes VS.  In my case, VS crashing on startup began just after I'd installed vsClojure. To fix it: I ran
  devenv.exe /SafeMode
VS loaded, and I found vsClojure disabled. I uninstalled vsClojure and restarted. 

Here are the details from the event log. The Source of this error is the .net runtime:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at vsClojure.Metadata..ctor()
   at ClojureExtension.Editor.Intellisense.HippieCompletionSource.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by frankhale** [comment]
Installation stability issues seem to be the primary concern right now. Any assistance you guys can give would be greatly appreciated.
