### ISSUE TITLE
TypeInitializationException was unhandled

### ISSUE THREAD

**Issue by johnjelinek** [vsClojure/vsClojure#95]
`ns.clj`:

```
(ns my.namespace
  (:gen-class
   :methods [[somethings [int] int]]))

(defn -somethings [x] (#(* % 2) x))
```

I added a reference in my C# project to the Clojure project in the solution.

`Program.cs`:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var ns = new my.@namespace();
            Console.WriteLine(ns.somethings(5));
            Console.ReadLine();
        }
    }
}
```

This builds appropriately, but when I run it, I get this:

```
System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'my.namespace' threw an exception.
  Source=log-analysis
  TypeName=my.namespace
  StackTrace:
       at my.namespace..ctor()
       at ConsoleApplication1.Program.Main(String[] args) in c:\Users\jjelinek\Documents\Visual Studio 2013\Projects\log-analysis\ConsoleApplication1\Program.cs:line 13
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.IO.FileNotFoundException
       HResult=-2147024894
       Message=Could not locate my.namespace.clj.dll or my/namespace.clj on load path.
       Source=Clojure
       StackTrace:
            at clojure.lang.RT.load(String relativePath, Boolean failIfNotFound)
            at clojure.lang.RT.load(String relativePath)
            at clojure/core$load$fn__17179__17183.invoke()
            at clojure/core$load__17186.doInvoke(Object )
            at clojure.lang.RestFn.invoke(Object arg1)
            at clojure.lang.Var.invoke(Object arg1)
            at my.namespace..cctor()
       InnerException: 
```

How do I get my clj/dll into the load path?

**Comment by frankhale** [comment]
I'm looking at this now.

**Comment by frankhale** [comment]
I can definitely reproduce this. After checking the bin\Debug folder of the compiled Clojure code I can see that it's not building the DLL and is only building the EXE. If my research is correct when you use gen-class the Clojure compiler is supposed to build a DLL and an EXE. When the C# code is trying to call the Clojure function it cannot find the DLL and we get this error. Now, that said, I tried replacing the Clojure.Compiler and runtime provided by vsClojure with the nuget version of Clojure but I exposed another problem and building broke. I suspect that the args being passed to the Clojure.Compiler are causing the DLL not to be built. I remember some talk of having the Clojure.Compiler build just one file but the patch to make that happen was reversed. I wonder if vsClojure is using a custom build compiler and this is exposing a problem? I need to play around with this some more. I'm labeling this a bug because the functionality seems broken right out of the box.

**Comment by frankhale** [comment]
I've been messing with this for a while and after hacking the cljproj and replacing the Clojure runtime with the runtime that is provided by the Nuget Clojure package I was able to finally get it to produce both the DLL and the EXE after compiling the code. That said, I've found another problem and that is that when C# calls the Clojure function it thinks that too many arguments are passed to the function call. I actually was playing with this last night as well and did some research and found a blog post that is relevant and which the blogger talks about the wackiness of calling Clojure code from C#. You can read that blog post here:

http://www.myclojureadventure.com/2011_12_01_archive.html

Here is the error I get with your code (although my namespace name is different everything else is the same):

```
Unhandled Exception: clojure.lang.ArityException: Wrong number of args (2) passed to: program$-somethings
   at clojure.lang.AFn.invoke(Object arg1, Object arg2)
   at program.somethings(Int32 )
   at ConsoleApplication1.Program.Main(String[] args) 
```

**Comment by speige** [comment]
I'm not sure you're coding this quite right. I am able to reproduce it with your code, but I change it around to make it work.

#1) when using gen-class, the name of the .clj file needs to match the name of the generated class. It should not be ns.clj, it should be ns.namespace.clj -> However, the MSBuild template gets confused by the extra period in the filename, I'll see about fixing that, but in the meantime, please use a name without a period, like "test". (This will essentially give the class no namespace, so you won't need a using statement in c#)

#2) The code should look like this:

(ns test ; notice class name matches file name
  (:gen-class
   :methods [[somethings [Int64] Int64]])) ; notice Int64

(defn -somethings [this x](#%28* % 2%29 x)) ; notice this

By making these changes, I was able to get it to work successfully.

**Comment by johnjelinek** [comment]
All the Clojure docs I've read say that namespaces that aren't qualified
with a . (ie: a.b) are bad code smells. Can you support the
namespace/using scenarios?

**Comment by frankhale** [comment]
Is using 'this' necessary because the code is being compiled to an
Assembly? Is that something special just for ClojureCLR? I haven't seen
code like that in Clojure JVM but maybe it is also used there as well.

**Comment by speige** [comment]
"this" can be any variable name of your choice, but the parameter is definitely required for class instance methods. I haven't coded much Clojure on the JVM, so I don't know if this is a difference between the two. David Miller would be the best to ask about that.

**Comment by frankhale** [comment]
Okay, do you know of any references that could point to why it's needed? It seems confusing to me and I ran into this issue before and it was not obvious how to call my code from C# because of the parameter mismatch.

**Comment by speige** [comment]
Well, it definitely is useful to have "this" available in Clojure for class instance methods, in order to get access to other member variables & methods. How do you get to member variables to it from the JVM?

As to why this is different than the JVM, you'd have to ask David Miller on gplus.to/clojureclr
